### ISSUE TITLE
Error while setting up ! Help needed ! 

### ISSUE THREAD

**Issue by ankurgaur** [BasicWolf/archived-kaylee#10]
Hey, while setting up and running the demo project , i came across this error . If you could look into it and guide me in the right direction .Thanks :)

---

Building Kaylee environment...
- Copying Kaylee test server files...
- Building hashcracker...
- Building montecarlopi...
- Building humanocr...
- Building pingpong...
  Launching Kaylee development/testing server...
  Settings error or object was not found: "ClientSessionDataManager"

**Comment by ankurgaur** [comment]
Nevermind  Solved it :)

**Comment by BasicWolf** [comment]
Glad that there are people interested in the project :)
